### ISSUE TITLE
The project cannot sync correctly

### ISSUE THREAD

**Issue by huanmeng-qwq** [jpenilla/run-task#88]
[The project cannot sync correctly](https://github.com/Rollczi/LiteCommands/blob/master/litecommands-adventure-platform/build.gradle.kts)

IntelliJ IDEA 2024.2.1 (Ultimate Edition)
K2 mode
Gradle(Wrapper): 8.10.2
Project JDK: Azul Zulu 21

```kts
plugins {
    id("java")
    id("com.gradleup.shadow") version "8.3.5"
    id("net.minecrell.plugin-yml.bukkit") version "0.6.0"
    id("xyz.jpenilla.run-paper") version "2.3.1"
}

version = "3.9.1"

repositories {
    mavenCentral()
    maven { url = uri("https://repo.panda-lang.org/releases/") }
    maven { url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/") }
}

dependencies {
    compileOnly("org.spigotmc:spigot-api:1.20.2-R0.1-SNAPSHOT")

    // implementation("dev.rollczi:litecommands-bukkit:3.9.1") // <-- uncomment in your project
    // implementation("dev.rollczi:litecommands-adventure-platform:3.9.1") // <-- uncomment in your project
    implementation("net.kyori:adventure-platform-bukkit:4.3.0")
    implementation("net.kyori:adventure-text-minimessage:4.14.0")

    implementation(project(":litecommands-bukkit")) // don't use this line in your build.gradle
    implementation(project(":litecommands-adventure-platform")) // don't use this line in your build.gradle
}

val pluginName = "ExampleAdventurePlugin"
val packageName = "dev.rollczi.example.bukkit.adventure"

bukkit {
    main = "$packageName.$pluginName"
    apiVersion = "1.13"
    author = "Rollczi"
    name = pluginName
    version = "${project.version}"
}

tasks.shadowJar {
    archiveFileName.set("$packageName v${project.version}.jar")

    listOf(
        "dev.rollczi.litecommands",
        "net.kyori",
    ).forEach { relocate(it, "$packageName.libs.$it") }
}

sourceSets.test {
    java.setSrcDirs(emptyList<String>())
    resources.setSrcDirs(emptyList<String>())
}

tasks.runServer {
    minecraftVersion("1.21")
}

```

```
> Task :buildSrc:generateScriptPluginAdapters UP-TO-DATE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:compileKotlin
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE

> Configure project :litecommands-fabric
Fabric Loom: 1.8.12

> Configure project :examples:fabric
Fabric Loom: 1.8.12

> Configure project :examples:sponge
SpongePowered Plugin 'GRADLE' Toolset Version '2.2.0'

> Task :litecommands-fabric:ideaSyncTask SKIPPED
> Task :examples:fabric:ideaSyncTask SKIPPED
> Task :prepareKotlinBuildScriptModel UP-TO-DATE
Download https://plugins.gradle.org/m2/com/gradle/develocity-gradle-plugin/3.17.6/develocity-gradle-plugin-3.17.6-sources.jar, took 554 ms

FAILURE: Build failed with an exception.

* What went wrong:
Could not create task ':examples:bukkit-adventure-platform:runServer'.
Could not create task of type 'RunServer'.
Cannot set the value of property 'downloadsApiService' of type xyz.jpenilla.runtask.service.DownloadsAPIService using a provider of type xyz.jpenilla.runtask.service.DownloadsAPIServiceImpl.

* Try:
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

* Exception is:
com.intellij.openapi.externalSystem.model.ExternalSystemException: Could not create task ':examples:bukkit-adventure-platform:runServer'.
Could not create task of type 'RunServer'.
Cannot set the value of property 'downloadsApiService' of type xyz.jpenilla.runtask.service.DownloadsAPIService using a provider of type xyz.jpenilla.runtask.service.DownloadsAPIServiceImpl.
	at com.intellij.gradle.toolingExtension.impl.modelAction.GradleModelFetchAction.executeAction(GradleModelFetchAction.java:254)
	at com.intellij.gradle.toolingExtension.impl.modelAction.GradleModelFetchAction.doExecute(GradleModelFetchAction.java:143)
	at ...............................
	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.lambda$execute$0(RunAsWorkerThreadBuildActionExecutor.java:36)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:263)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:127)
	at ..........................
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'RunServer'.
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:95)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:82)
	at org.gradle.........................
	... 178 more
Caused by: java.lang.IllegalArgumentException: Cannot set the value of property 'downloadsApiService' of type xyz.jpenilla.runtask.service.DownloadsAPIService using a provider of type xyz.jpenilla.runtask.service.DownloadsAPIServiceImpl.
	at org.gradle.api.internal.provider.AbstractMinimalProvider.asSupplier(AbstractMinimalProvider.java:158)
	at org.gradle.api.internal.provider.DefaultProperty.convention(DefaultProperty.java:133)
	at xyz.jpenilla.runpaper.task.RunServer.init(RunServer.kt:61)
	at xyz.jpenilla.runtask.task.AbstractRun.init0(AbstractRun.kt:100)
	at xyz.jpenilla.runtask.task.AbstractRun.<init>(AbstractRun.kt:92)
	at xyz.jpenilla.runtask.task.RunWithPlugins.<init>(RunWithPlugins.kt:45)
	at xyz.jpenilla.runpaper.task.RunServer.<init>(RunServer.kt:37)
	at xyz.jpenilla.runpaper.task.RunServer_Decorated.<init>(Unknown Source)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:2107)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:544)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:65)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstanceWithDisplayName(DependencyInjectingInstantiator.java:51)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:88)
	... 188 more



BUILD FAILED in 50s
10 actionable tasks: 2 executed, 8 up-to-date

The build scan was not published due to a configuration problem.
.........

```

**Comment by jpenilla** [comment]
Not a run-task issue, your configuration is triggering a Gradle bug. See bullet point 4 under notes here: https://github.com/PaperMC/paperweight-test-plugin/blob/32fbd4de765c3bfc83c38a0bd122aea62c199f83/README.md
